name: Documentation

on:
  push:
    paths:
    - 'docs/source/*'

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: install
      run: pip install --user sphinx
    - name: build
      run: |
        cd docs
        make html
