name: Documentation

on:
  push:
    paths:
    - 'docs/source/*'

jobs:
  cmake:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install
      run: apt-get install python3-sphinx
    - name: cmake
      run: |
        cd docs
        make html
