name: Documentation

on:
  push:
    paths:
    - 'docs/source/*'

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: install
      run: |
        pip install sphinx
        pip install recommonmark
        echo "::add-path::C:\Users\runneradmin\AppData\Roaming\Python\Python37\Scripts"
    - name: build
      run: |
        cd docs
        make html
